#!/usr/bin/env python

import sys, os, shutil, subprocess, multiprocessing, argparse, logging, stem, functools, time
from signal import signal, SIGINT, SIG_IGN, SIGTERM
from itertools import cycle
from stem import process, control
from stem.control import EventType, Controller
from stem.util import str_tools

DESCRIPTION="""
A utility to track the performance of hidden services in Tor.
"""

DOWNLOAD_SIZES=["50 KiB", "1 MiB", "5 MiB"]

TGEN_SERVER_CONF="""<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key attr.name="time" attr.type="string" for="node" id="d1" />
  <key attr.name="serverport" attr.type="string" for="node" id="d0" />
  <graph edgedefault="directed">
    <node id="start">
      <data key="d0">8888</data>
      <data key="d1">0</data>
    </node>
  </graph>
</graphml>"""

TGEN_CLIENT_CONF_TEMPLATE="""<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key attr.name="socksproxy" attr.type="string" for="node" id="d7" />
  <key attr.name="serverport" attr.type="string" for="node" id="d6" />
  <key attr.name="peers" attr.type="string" for="node" id="d5" />
  <key attr.name="type" attr.type="string" for="node" id="d4" />
  <key attr.name="protocol" attr.type="string" for="node" id="d3" />
  <key attr.name="size" attr.type="string" for="node" id="d2" />
  <key attr.name="count" attr.type="string" for="node" id="d1" />
  <key attr.name="time" attr.type="string" for="node" id="d0" />
  <graph edgedefault="directed">
    <node id="start">
      <data key="d5">{0}:80</data>
      <data key="d6">8889</data>
      <data key="d7">localhost:9001</data>
    </node>
    <node id="transfer">
      <data key="d3">tcp</data>
      <data key="d4">get</data>
      <data key="d2">{1}</data>
    </node>
    <node id="end">
      <data key="d0">1</data>
    </node>
    <edge source="start" target="transfer" />
    <edge source="transfer" target="end" />
    <edge source="end" target="start" />
  </graph>
</graphml>"""

logging.basicConfig(format='[%(asctime)s] [onionperf] [%(levelname)s] %(message)s', level=logging.INFO)
logging.getLogger("stem").setLevel(logging.WARN)

class OnionPerf:
    torpath = None
    tgenpath = None
    burst_interval = None
    burst_num = None
    done_event = None
    s_tor_datadir = None
    s_tor_hsdir = None
    s_tor_onionurl = None
    s_tgen_process = None
    s_tor_logger_process = None
    c_tgen_process = None
    c_tor_logger_process = None

    def __init__(self, args):
        self.torpath = args.torpath
        self.tgenpath = args.tgenpath
        self.burst_interval = args.burst_interval
        self.burst_num = args.burst_num
        self.done_event = multiprocessing.Event()

    def run(self):
        # if ctrl-c is pressed, shutdown child processes properly
        try:
            logging.info("Starting tgen server...")
            self.__start_tgen_server()
            logging.info("Starting tor server...")
            self.__start_tor_server()
            logging.info("Starting tor client...")
            self.__start_tor_client()
            logging.info("Starting tor loggers...")
            self.__start_tor_loggers()
            logging.info("Pausing for 30 seconds to publish hidden service descriptor...")
            time.sleep(30)
            logging.info("Starting tgen client...")
            self.__start_tgen_client()

            logging.info("Everything is running; sleeping now...")
            time.sleep(3600*24*30)

        except KeyboardInterrupt:
            logging.info("Interrupt received")

        finally:
            logging.info("Cleaning up child processes now...")

            logging.disable(logging.INFO)
            self.done_event.set()
            if self.c_tgen_process is not None: self.c_tgen_process.join()
            if self.s_tgen_process is not None: self.s_tgen_process.join()
            if self.c_tor_logger_process is not None: self.c_tor_logger_process.join()
            if self.s_tor_logger_process is not None: self.s_tor_logger_process.join()
            time.sleep(1)
            logging.disable(logging.NOTSET)

            logging.info("Child processes terminated")

            if self.s_tor_hsdir is not None:
                #self.server_tor_ctl.remove_hidden_service(self.server_hsdir)
                shutil.rmtree(self.s_tor_hsdir)

            logging.info("Child process cleanup complete!")
            logging.info("Exiting")

    def __start_tgen_server(self):
        self.s_tgen_process = multiprocessing.Process(target=OnionPerf.__tgen_server_main, args=(self,))
        self.s_tgen_process.start()

    def __tgen_server_main(self):
        signal(SIGINT, SIG_IGN) # ignore interrupts
        tgen_dir = ".onionperf/server/tgen"
        if not os.path.exists(tgen_dir): os.makedirs(tgen_dir)
        conffile = "{0}/tgen.graphml.xml".format(tgen_dir)
        if not os.path.exists(conffile):
            with open(conffile, 'wb') as f: print >>f, TGEN_SERVER_CONF,
        with open("{0}/tgen.log".format(tgen_dir), 'a') as logf:
            p = None
            while not self.done_event.is_set():
                p = subprocess.Popen([self.tgenpath, conffile], stdout=logf, stderr=logf)
                while not self.done_event.wait(5): # while the timeout triggers
                    if p.poll() is not None: # process has terminated
                        p.wait() # collect child
                        p = None # clear
                        break # break out inner loop and restart process
            # if interupted and proc is still running, kill it
            if p is not None and p.poll() is None:
                p.terminate()
                p.wait()

    def __start_tgen_client(self):
        self.c_tgen_process = multiprocessing.Process(target=OnionPerf.__tgen_client_main, args=(self,))
        self.c_tgen_process.start()

    def __tgen_client_main(self):
        signal(SIGINT, SIG_IGN) # ignore interrupts
        tgen_dir = ".onionperf/client/tgen"
        if not os.path.exists(tgen_dir): os.makedirs(tgen_dir)
        conffile = "{0}/tgen.graphml.xml".format(tgen_dir)
        with open("{0}/tgen.log".format(tgen_dir), 'a') as logf:
            sizes = cycle(DOWNLOAD_SIZES)
            p = None
            count = 0
            while not self.done_event.is_set():
                if os.path.exists(conffile): os.remove(conffile)
                with open(conffile, 'wb') as f: print >>f, TGEN_CLIENT_CONF_TEMPLATE.format(self.s_tor_onionurl, sizes.next()),
                p = subprocess.Popen([self.tgenpath, conffile], stdout=logf, stderr=logf)
                while not self.done_event.wait(5): # while the timeout triggers
                    if p.poll() is not None: # process has terminated
                        p.wait() # collect child
                        p = None # clear
                        break # break out inner loop and restart process
                count += 1
                if count >= self.burst_num:
                    time.sleep(self.burst_interval)
                    count = 0
            # if interupted and proc is still running, kill it
            if p is not None and p.poll() is None:
                p.terminate()
                p.wait()

    def __start_tor_loggers(self):
        self.s_tor_logger_process = multiprocessing.Process(target=OnionPerf.__tor_logger_main, args=(self, 9050, ".onionperf/server/tor/tor.ctl.log"))
        self.s_tor_logger_process.start()
        self.c_tor_logger_process = multiprocessing.Process(target=OnionPerf.__tor_logger_main, args=(self, 9051, ".onionperf/client/tor/tor.ctl.log"))
        self.c_tor_logger_process.start()

    def __tor_logger_main(self, ctlport, logpath):
        signal(SIGINT, SIG_IGN) # ignore interrupts
        with open(logpath, 'a') as logf:
            with stem.control.Controller.from_port(port = ctlport) as torctl:
                event_handler = functools.partial(OnionPerf.__handle_tor_event, self, logf, )
                torctl.authenticate()
                torctl.add_event_listener(event_handler, stem.control.EventType.ORCONN, stem.control.EventType.CIRC, stem.control.EventType.STREAM, stem.control.EventType.BW, stem.control.EventType.GUARD, stem.control.EventType.INFO, stem.control.EventType.NOTICE, stem.control.EventType.WARN, stem.control.EventType.ERR, stem.control.EventType.HS_DESC, stem.control.EventType.BUILDTIMEOUT_SET, stem.control.EventType.DESCCHANGED, stem.control.EventType.NEWCONSENSUS, stem.control.EventType.NEWDESC, stem.control.EventType.STATUS_CLIENT, stem.control.EventType.STATUS_GENERAL, stem.control.EventType.STATUS_SERVER)
                #torctl.add_event_listener(event_handler, stem.control.EventType.CONN_BW, stem.control.EventType.CIRC_BW, stem.control.EventType.STREAM_BW, stem.control.EventType.TB_EMPTY, stem.control.EventType.HS_DESC_CONTENT)
                self.done_event.wait()
        time.sleep(1)

    def __handle_tor_event(self, logf, event):
        s = time.time()
        t = time.localtime(s)
        print >>logf, "{0} {1} {2}".format(time.strftime("%Y-%m-%d %H:%M:%S"), s, event.raw_content()),

    def __start_tor_client(self):
        self.c_tor_datadir = ".onionperf/client/tor/data"
        if not os.path.exists(self.c_tor_datadir): os.makedirs(self.c_tor_datadir)
        os.chmod(self.c_tor_datadir, 0700)

        config = {
            'ORPort': '0',
            'DirPort': '0',
            'ControlPort': '9051',
            'SocksPort': '9001',
            'SocksListenAddress': '127.0.0.1',
            'ClientOnly': '1',
            'FascistFirewall': '1',
            'WarnUnsafeSocks': '0',
            'SafeLogging': '0',
            'MaxCircuitDirtiness': '10 seconds',
            'DataDirectory': self.c_tor_datadir,
            'Log': [
                'NOTICE stdout',
                #'INFO file .onionperf/client/tor/tor.log'.format(self.c_tor_datadir),
            ],
        }

        tor_p = stem.process.launch_tor_with_config(config, tor_cmd=self.torpath, completion_percent=100, init_msg_handler=None, timeout=None, take_ownership=True)

    def __start_tor_server(self):
        self.s_tor_datadir = ".onionperf/server/tor/data"
        if not os.path.exists(self.s_tor_datadir): os.makedirs(self.s_tor_datadir)
        os.chmod(self.s_tor_datadir, 0700)

        self.s_tor_hsdir = ".onionperf/server/tor/hs"
        if not os.path.exists(self.s_tor_hsdir): os.makedirs(self.s_tor_hsdir)
        os.chmod(self.s_tor_hsdir, 0700)

        config = {
            'ORPort': '0',
            'DirPort': '0',
            'ControlPort': '9050',
            'SocksPort': '9000',
            'SocksListenAddress': '127.0.0.1',
            'ClientOnly': '1',
            'FascistFirewall': '1',
            'WarnUnsafeSocks': '0',
            'SafeLogging': '0',
            'MaxCircuitDirtiness': '10 seconds',
            'DataDirectory': self.s_tor_datadir,
            'HiddenServiceDir': self.s_tor_hsdir,
            'HiddenServicePort': '80 127.0.0.1:8888',
            'Log': [
                'NOTICE stdout',
                #'INFO file .onionperf/server/tor/tor.log',
            ],
        }

        tor_p = stem.process.launch_tor_with_config(config, tor_cmd=self.torpath, completion_percent=100, init_msg_handler=None, timeout=None, take_ownership=True)

        with open("{0}/hostname".format(self.s_tor_hsdir), 'r') as f:
            self.s_tor_onionurl = f.readline().strip()

def main():
    # construct the options
    parser = argparse.ArgumentParser(
        description=DESCRIPTION, 
        formatter_class=argparse.RawTextHelpFormatter)

    parser.add_argument('-p', '--prefix', 
        help="""a STRING directory path prefix where onionperf will run""", 
        action="store", type=str, metavar="STRING",
        dest="prefix", default=os.getcwd())

    parser.add_argument('--tor', 
        help="""a STRING path to a tor binary""", 
        action="store", type=str, metavar="STRING",
        dest="torpath", default=None)

    parser.add_argument('--tgen', 
        help="""a STRING path to a tgen binary""", 
        action="store", type=str, metavar="STRING",
        dest="tgenpath", default=None)

    parser.add_argument('-t', 
        help="""the number N of seconds to sleep between download phases""", 
        action="store", type=int, metavar="N",
        dest="burst_interval", default=10)

    parser.add_argument('-n', 
        help="""the number N of downloads to perform during each download phase""", 
        action="store", type=int, metavar="N",
        dest="burst_num", default=15)

    # get args
    args = parser.parse_args()

    # test paths
    args.torpath = find_path_helper(args.torpath, "tor")
    if args.torpath is not None: args.tgenpath = find_path_helper(args.tgenpath, "tgen")

    # validate paths and run
    if args.torpath is not None and args.tgenpath is not None:
        args.prefix = os.path.abspath(os.path.expanduser(args.prefix))
        if not os.path.exists(args.prefix): os.makedirs(args.prefix)
        os.chdir(args.prefix)
        op = OnionPerf(args)
        op.run()
    else: logging.info("Please fix path errors to continue")

def find_path_helper(binpath, defaultname):
    # find the path to tor
    if binpath is not None:
        binpath = os.path.abspath(os.path.expanduser(binpath))
    else:
        w = which_helper(defaultname)
        if w is not None:
            binpath = os.path.abspath(os.path.expanduser(w))
        else:
            logging.error("You did not specify a path to a '{0}' binary, and one does not exist in your PATH".format(defaultname))
            return None
    # now make sure the path exists
    if os.path.exists(binpath):
        logging.info("Using '{0}' binary at {1}".format(defaultname, binpath))
    else:
        logging.error("Path to '{0}' binary does not exist: {1}".format(defaultname, binpath))
        return None
    # we found it and it exists
    return binpath

def which_helper(program):
    def is_exe(fpath):
        return os.path.isfile(fpath) and os.access(fpath, os.X_OK)
    fpath, fname = os.path.split(program)
    if fpath:
        if is_exe(program):
            return program
    else:
        for path in os.environ["PATH"].split(os.pathsep):
            exe_file = os.path.join(path, program)
            if is_exe(exe_file):
                return exe_file
    return None

if __name__ == '__main__': sys.exit(main())
